export const SUBTITLES = {
  CALIFORNIA_RESOURCE_AND_REFERRAL_NETWORK: 'California Resource and Referral Network',
  CALIFORNIA_COVID19_CHILDCARE_RESPONSE: 'California Covid-19 Childcare Response',
  CALIFORNIA_PARENT_AND_FAMILY_RESOURCES: 'California Parent and Family Resources',
  FAMILY_CHILD_CARE_HOME_LICENSING_INFORMATION: 'Family Child Care Home Licensing Information'
};

const CRRN_PHONE = '(415) 882-0234';
const CALIFONRIA_COVID_CHILDCARE_RESPONSE_URL = 'https://covid19.ca.gov/childcare/';
const CALIFONRIA_PARENT_AND_FAMILY_RESOURCES_URL = 'https://www.cdss.ca.gov/inforesources/child-care-licensing/resources-for-parents';
const FAMILY_CHILDCARE_HOME_LICENSING_INFO_URL = 'https://www.cdss.ca.gov/inforesources/child-care-licensing/how-to-become-licensed/fcch-licensing-information';

export const RESOURCES = {
  [SUBTITLES.CALIFORNIA_RESOURCE_AND_REFERRAL_NETWORK]: CRRN_PHONE,
  [SUBTITLES.CALIFORNIA_COVID19_CHILDCARE_RESPONSE]: CALIFONRIA_COVID_CHILDCARE_RESPONSE_URL,
  [SUBTITLES.CALIFORNIA_PARENT_AND_FAMILY_RESOURCES]: CALIFONRIA_PARENT_AND_FAMILY_RESOURCES_URL,
  [SUBTITLES.FAMILY_CHILD_CARE_HOME_LICENSING_INFORMATION]: FAMILY_CHILDCARE_HOME_LICENSING_INFO_URL,
};
