// flow-typed signature: cb024cef998ec086306381f571541c96
// flow-typed version: <<STUB>>/@fortawesome/pro-duotone-svg-icons_v5.10.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-duotone-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-duotone-svg-icons' {
  declare module.exports: any;
}