// flow-typed signature: 09320937a85401306a3ec3c090feb5c6
// flow-typed version: <<STUB>>/connected-react-router_v6.3.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connected-react-router' {
  declare module.exports: any;
}

declare module 'connected-react-router/immutable' {
  declare module.exports: any;
}
