// flow-typed signature: ea09d4d0784dce5e05f2d3d1c31b3df9
// flow-typed version: <<STUB>>/file-saver_v2.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-saver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-saver' {
  declare module.exports: any;
}
