// flow-typed signature: e1e7490134c7ad400b1af9af752dfdf5
// flow-typed version: <<STUB>>/lattice-ui-kit_v0.2.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-ui-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-ui-kit' {
  declare module.exports: any;
}
