// flow-typed signature: 6474f478f9f74ec952a76b13f5c7bb97
// flow-typed version: <<STUB>>/react-scrolllock_v5.0.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrolllock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrolllock' {
  declare module.exports: any;
}
