// flow-typed signature: d87f0f2109210cf331ca30fb368fe6f1
// flow-typed version: <<STUB>>/react-mapbox-gl_v4.8.6/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mapbox-gl' {
  declare module.exports: any;
}
