// flow-typed signature: 593c4aa66c56b7fcbea033fc33b67728
// flow-typed version: <<STUB>>/recharts_v1.6.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recharts' {
  declare module.exports: any;
}
