// flow-typed signature: d8d6c3d1f68e0bcda78082ec11be90c3
// flow-typed version: <<STUB>>/@atlaskit/datetime-picker_v6.3.21/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/datetime-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/datetime-picker' {
  declare module.exports: any;
}
