// flow-typed signature: bf171faedc37bdae920fbb741417b77b
// flow-typed version: <<STUB>>/@atlaskit/modal-dialog_v6.0.12/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/modal-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/modal-dialog' {
  declare module.exports: any;
}
