name: deploy-staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: npm config
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" "$FONTAWESOME_NPM_AUTH_TOKEN"

      - name: npm ci
        run: npm ci

      - name: npm run build:prod
        run: npm run build:prod -- --env.basePath=child-care --env.mapboxToken=${{ secrets.CHILD_CARE_STAGING_MAPBOX_TOKEN }}

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEPLOYER_AWS_REGION }}

      - name: deploy to s3
        run: |
          aws s3 rm --recursive s3://staging.openlattice.com/child-care/
          aws s3 cp --recursive build/ s3://staging.openlattice.com/child-care/

      - name: clear cloudflare cache
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID_MYCHILDCARE }}/purge_cache" \
            -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}" \
            -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://staging.openlattice.com/child-care"]}'
